stages:
- build
- push
- update-manifest

include:
- local: gitlab-ci/templates/api-gateway.yml
- local: gitlab-ci/templates/frontend.yml
- local: gitlab-ci/templates/user-service.yml
- local: gitlab-ci/templates/survey-service.yml
- local: gitlab-ci/templates/auth-service.yml
- local: gitlab-ci/templates/payment-service.yml

